### ISSUE TITLE
Error in admin panel

### ISSUE THREAD

**Issue by denysdesign** [alg5/adminnotifications#2]
PHP 5.3.3
PHPBB 3.1.6

Error:

Fatal error: Uncaught exception 'Exception' with message 'DateTime::__construct() [<a href='datetime.--construct'>datetime.--construct</a>]: Failed to parse time string (@) at position 0 (@): Unexpected character' in /var/www/forum/phpbb/datetime.php:50 Stack trace: #0 /var/www/forum/phpbb/datetime.php(50): DateTime->__construct('@', Object(DateTimeZone)) #1 /var/www/forum/phpbb/user.php(728): phpbb\datetime->__construct(Object(phpbb\user), '@', Object(DateTimeZone)) #2 /var/www/forum/ext/alg/adminnotifications/acp/acp_adminnotifications_module.php(44): phpbb\user->format_date(NULL, 'd/m/Y H:i') #3 /var/www/forum/includes/functions_module.php(674): alg\adminnotifications\acp\acp_adminnotifications_module->main('\alg\adminnotif...', 'adminnotificati...') #4 /var/www/forum/adm/index.php(81): p_master->load_active() #5 {main} thrown in /var/www/forum/phpbb/datetime.php on line 50

**Comment by alg5** [comment]
this error not reproduced for me
@joomla-ua,   please, check the table phpbb_adminnotification, field 'create_time'
do you have null value for this field for each rows or in one row or in some rows?
I didn't got null value,  anyway I made fix for your case
